apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginxreplica
  name: nginxreplica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxreplica
  template:
    metadata:
      labels:
        app: nginxreplica
    spec:
      containers:
      - image: nginx:latest
        name: nginx