apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbdeploy_edit
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role_deploy_edit
  apiGroup: rbac.authorization.k8s.io