apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbdeploy_view
  namespace: default
subjects:
- kind: User
  name: deploy_view
  namespace: default
roleRef:
  kind: Role
  name: role_deploy_view
  apiGroup: rbac.authorization.k8s.io