apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbprod_view
  namespace: prod
subjects:
- kind: User
  name: prod_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role_prod_view
  apiGroup: rbac.authorization.k8s.io